openapi: "3.1.0"
info:
  title: Todo List API
  version: 1.0.0
  description: A simple API for managing todo lists.

paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieves a list of all tasks.
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              example:
                - $ref: "#/components/schemas/Task"

    post:
      summary: Create a new task
      description: Creates a new task.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewTask"
      responses:
        "201":
          description: Task created successfully
          content:
            application/json:
              example:
                $ref: "#/components/schemas/Task"

  /tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID of the task to retrieve or update.
        schema:
          type: integer
    get:
      summary: Get a task by ID
      description: Retrieves a specific task by its ID.
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              example:
                $ref: "#/components/schemas/Task"
        "404":
          description: Task not found
          content:
            application/json:
              example:
                $ref: "#/components/responses/TaskNotFound"

    put:
      summary: Update a task
      description: Updates a specific task by its ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTask"
      responses:
        "200":
          description: Task updated successfully
          content:
            application/json:
              example:
                $ref: "#/components/schemas/Task"
        "404":
          description: Task not found
          content:
            application/json:
              example:
                $ref: "#/components/responses/TaskNotFound"

    delete:
      summary: Delete a task
      description: Deletes a specific task by its ID.
      responses:
        "204":
          description: Task deleted successfully
        "404":
          description: Task not found
          content:
            application/json:
              example:
                $ref: "#/components/responses/TaskNotFound"

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier for the task.
        title:
          type: string
          description: The title of the task.
        completed:
          type: boolean
          description: Indicates whether the task is completed or not.
      required:
        - title
        - completed

    NewTask:
      type: object
      properties:
        title:
          type: string
          description: The title of the new task.
      required:
        - title

    UpdateTask:
      type: object
      properties:
        title:
          type: string
          description: The updated title of the task.
        completed:
          type: boolean
          description: The updated completion status of the task.
      required:
        - title
        - completed

  responses:
    TaskNotFound:
      description: Task not found
      content:
        application/json:
          example:
            error: Task not found

    BadRequest:
      description: Bad request
      content:
        application/json:
          example:
            error: Bad request, please check your request body

    Unauthorized:
      description: Unauthorized request
      content:
        application/json:
          example:
            error: Unauthorized request
