// Code generated by ogen, DO NOT EDIT.
package oas

type DeleteTaskRes interface {
	deleteTaskRes()
}

type GetTaskByIdRes interface {
	getTaskByIdRes()
}

type UpdateTaskRes interface {
	updateTaskRes()
}
