// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTask implements createTask operation.
//
// Creates a new task.
//
// POST /tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req *NewTask) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTask implements deleteTask operation.
//
// Deletes a specific task by its ID.
//
// DELETE /tasks/{id}
func (UnimplementedHandler) DeleteTask(ctx context.Context, params DeleteTaskParams) (r DeleteTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTaskById implements getTaskById operation.
//
// Retrieves a specific task by its ID.
//
// GET /tasks/{id}
func (UnimplementedHandler) GetTaskById(ctx context.Context, params GetTaskByIdParams) (r GetTaskByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTasks implements getTasks operation.
//
// Retrieves a list of all tasks.
//
// GET /tasks
func (UnimplementedHandler) GetTasks(ctx context.Context) (r []Task, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTask implements updateTask operation.
//
// Updates a specific task by its ID.
//
// PUT /tasks/{id}
func (UnimplementedHandler) UpdateTask(ctx context.Context, req *UpdateTask, params UpdateTaskParams) (r UpdateTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
